spring:
  application:
    name: wordtest-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cxyp?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

server:
  port: 8080
